name: Lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install deps
        run: forge install

      - name: Build contracts
        run: forge build

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          # foundry-rs/foundry-toolchain@v1 will install foundry outside of the slither-action container.
          # As a result, we need to run `forge build` before running slither, and then run slither with
          # `ignore-compile: true`
          # The action might eventually package Foundry: https://github.com/crytic/slither-action/issues/5
          ignore-compile: true
          sarif: results.sarif
          target: .

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
